#!/bin/sh

# Set these paths appropriately

BIN="/Users/mac/Desktop/vscode/gromov/tree_tagger/bin"
CMD="/Users/mac/Desktop/vscode/gromov/tree_tagger/cmd"
LIB="/Users/mac/Desktop/vscode/gromov/tree_tagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/ukrainian-abbreviations
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/ukrainian.par

# do tokenization
$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
