#!/bin/sh

# Set these paths appropriately

BIN="/Users/mac/Desktop/vscode/gromov/tree_tagger/bin"
CMD="/Users/mac/Desktop/vscode/gromov/tree_tagger/cmd"
LIB="/Users/mac/Desktop/vscode/gromov/tree_tagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/romanian-abbreviations
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/romanian.par

$TOKENIZER -r -a $ABBR_LIST $* |
${CMD}/split-romanian.perl ${LIB}/romanian-tokens |
$TAGGER $OPTIONS $PARFILE
