#!/bin/sh

# Set these paths appropriately

BIN="/Users/mac/Desktop/vscode/gromov/tree_tagger/bin"
CMD="/Users/mac/Desktop/vscode/gromov/tree_tagger/cmd"
LIB="/Users/mac/Desktop/vscode/gromov/tree_tagger/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
