#!/bin/sh

# Set these paths appropriately

BIN="/Users/mac/Desktop/vscode/gromov/tree_tagger/bin"
CMD="/Users/mac/Desktop/vscode/gromov/tree_tagger/cmd"
LIB="/Users/mac/Desktop/vscode/gromov/tree_tagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/ancient-greek.par

$TOKENIZER $* |
# tagging
$TAGGER $OPTIONS $PARFILE

