#!/bin/sh

# Set these paths appropriately

BIN="/Users/mac/Desktop/vscode/gromov/tree_tagger/bin"
CMD="/Users/mac/Desktop/vscode/gromov/tree_tagger/cmd"
LIB="/Users/mac/Desktop/vscode/gromov/tree_tagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/greek-mwls.pl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/greek-abbreviations
PARFILE=${LIB}/greek.par

$TOKENIZER -a $ABBR_LIST $* |
$MWL |
# tagging
$TAGGER $OPTIONS $PARFILE

